### ISSUE TITLE
how to get expression matrix for gene and transcript level

### ISSUE THREAD

**Issue by alecervera** [BitSeq/BitSeq#18] opened 2016-04-06 11:22 UTC
Hi,
I am trying to incorporate BitSeq to our RNA-Seq pipeline, but I am stuck trying to produce similar expression matrices as produce by other tools for quantification. I am not using R, and want to know how to get an expression matrix in fpkms or tpm both at transcript and gene level. I have run the following commands:
$parseAlignment Aligned.toTranscriptome.out.bam --outFile mysample.prob --trSeqFile transcripts_82.fa --trInfoFile mysample.tr --uniform
$estimateExpression mysample.prob --outPrefix mysample --outType rpkm --trInfoFile mysample.tr
$getExpression mysample.prob -o mysample_genes -t mysample.tr mysample.rpkm

So, how do I get one single tpm or fpkm value for each gene and one for each transcript from the output files? The file mysample_genes seens to have a matrix of 58726 x 1000 ....

Thanks for any help with this

**Comment by mqbssppe** [comment] 2016-04-11 09:09
Hi,

the 58726 x 1000 matrix contains samples from the (approximate) posterior distribution of each transcript. In order to get summarize it try to run the command:

getVariance -o <outFileName>  mysample.rpkm

It will produce a file containing the mean and variance of expression level per transcript. (assuming that mysample.rpkm is the output file obtained from estimateExpression). So for your example:

estimateExpression mysample.prob -o mysample --outType RPKM -t data.tr -P 4
getVariance -o mysampleTRANSCRIPTS mysample.rpkm

--- > mean RPKM values are written to the 1st column of mysampleTRANSCRIPTS 

In order to obtain the corresponding files at the gene-level, assume that the file geneFile.txt contains gene names (one per transcript - at the same order with your data.tr file names)

getGeneExpression -o mysampleGENE.rpkm -t data.tr -G geneFile.txt mysample.rpkm
getVariance -o mysampleGENES mysampleGENE.rpkm

--- > mean gene-level RPKM values are written to the 1st column of mysampleGENES 


Panos

**Comment by ahonkela** [comment] 2017-03-22 08:10
Duplicate of #4, closing.

**Closed by ahonkela** 2017-03-22 08:10 UTC
Labels: duplicate
